# Generated by Django 3.2.7 on 2023-12-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydarzenie',
            name='data_rozpoczecia',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='data_zakonczenia',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
