# Generated by Django 3.2.7 on 2023-12-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20231207_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wydarzenie',
            name='autor',
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='data_rozpoczecia',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='data_zakonczenia',
            field=models.DateTimeField(),
        ),
    ]
