# Generated by Django 5.0 on 2023-12-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
                ("lokalizacja", models.CharField(max_length=255)),
                ("pojemnosc", models.IntegerField()),
                (
                    "dostepne_wydarzenie",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="events.wydarzenie",
                    ),
                ),
            ],
        ),
    ]
