# Generated by Django 5.0 on 2023-12-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("rooms", "0002_remove_sala_dostepne_wydarzenie"),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="dostepne_wydarzenie",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.wydarzenie",
            ),
        ),
    ]
