# Generated by Django 5.0 on 2023-12-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("rooms", "0003_sala_dostepne_wydarzenie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sala",
            name="dostepne_wydarzenie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.wydarzenie",
            ),
        ),
    ]
