# Generated by Django 5.0 on 2023-12-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_alter_sala_dostepne_wydarzenie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sala",
            name="dostepne_wydarzenie",
        ),
        migrations.AddField(
            model_name="sala",
            name="dostepne_wyposazenie",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sala",
            name="zdjecie",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
