# Generated by Django 3.2.7 on 2023-12-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_sala_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='status',
        ),
    ]
