# Generated by Django 5.0 on 2023-12-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0007_remove_sala_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sala",
            name="zdjecie",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
