# Generated by Django 5.0 on 2023-12-07 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0004_alter_wydarzenie_opis"),
        ("rooms", "0005_remove_sala_dostepne_wydarzenie_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rezerwacja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referencja_sala",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referencja_sala",
                        to="rooms.sala",
                    ),
                ),
                (
                    "referencja_wydarzenie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referencja_wydarzenie",
                        to="events.wydarzenie",
                    ),
                ),
            ],
        ),
    ]
