# Generated by Django 3.2.7 on 2023-12-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_wydarzenie_opis'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacja',
            name='czas_rozpoczecia',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacja_czas_rozpoczecia', to='events.wydarzenie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='czas_zakonczenia',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacja_czas_zakonczenia', to='events.wydarzenie'),
            preserve_default=False,
        ),
    ]
