# Generated by Django 3.2.7 on 2023-12-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20231207_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerwacja',
            name='czas_rozpoczecia',
        ),
        migrations.RemoveField(
            model_name='rezerwacja',
            name='czas_zakonczenia',
        ),
    ]
