# Generated by Django 3.2.7 on 2023-12-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_sala_status'),
        ('reservations', '0004_auto_20231207_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerwacja',
            name='referencja_sala',
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='referencja_sala',
            field=models.ManyToManyField(related_name='ref_sala', to='rooms.Sala'),
        ),
    ]
